#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "material"
    colorscheme_bg = "dark"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[custom_plugins]]
    name = "lilydjwg/colorizer"
    merged = false

[[custom_plugins]]
  name = "mhartington/oceanic-next"
  merged = 0

[[custom_plugins]]
  name =  "andybarilla/vim-colors-glacier" 
  merged = 0

[[layers]]
  name = "ui"
  enable_sidebar = true

[[layers]] 
  name = "colorscheme"

[[custom_plugins]] 
  name = "ryanoasis/vim-devicons"

[[custom_plugins]] 
  name = "preservim/nerdtree"

[[layers]]
  name = "lang#go"

[[layers]]
  name = "lang#java"

[[layers]]
name = "lang#javascript"

[[layers]]
  name = "lang#markdown"

[[layers]]
  name = "lang#python"

[[layers]]
  name = "lang#sh"

[[layers]]
  name = "lang#typescript"

[[layers]]
  name = "lsp"

[[layers]]
  name = "shell"

[[layers]]
  name = "ui"

[[layers]]
  name = "fuzzy"

[[layers]]
  name = "fzf"

[[layers]]
  name = "git"

[[layers]]
  name = "tools"

[[layers]]
  name = "VersionControl"

[[custom_plugins]]
name = "dracula/vim"
merged = 0
