---
baseURL: https://klw77491.live.dynatrace.com/api/v2/
apiToken: Api-Token dt0c01.24XPDJ5Q5FAUZYUS5KRVA2O5.OODQZR5L45SNBYCWY2NBCHSYKNBWXIAHB3JMDIMG6PKJRBSEYZPUJ6TADPX2RA3P
v1BaseURL: https://klw77491.live.dynatrace.com/api/v1/synthetic/monitors/
