---
apiVersion: openslo/v1alpha
kind: SLO
metadata:
  name: sloCreateCli
  displayName: test-cli-slo # optional
spec:
  description: a test slo # optional
  service: builtin:service.successes.server.rate  # name of the service to associate this SLO with
  indicator: # represents the Service Level Indicator (SLI)
    thresholdMetric: # represents the metric used to inform the Service Level Object in the objectives stanza
    source: string: # data source for the metric
      queryType: string # a name for the type of query to run on the data source
      query: string # the query to run to return the metric
  timeWindows:
    # exactly one item, one of possible rolling time window or calendar aligned
    # rolling time window
    - unit: Second
      count: numeric
      isRolling: true
    # or
    # calendar aligned time window
    - unit: Year | Quarter | Month | Week | Day
      count: numeric # count of time units for example count: 7 and unit: Day means 7 days window
      calendar:
        startTime: 2020-01-21 12:30:00 # date with time in 24h format, format without time zone
        timeZone: America/New_York # name as in IANA Time Zone Database
      isRolling: false # false or not defined
  budgetingMethod: Occurrences | Timeslices
  objectives: # see objectives below for details

payload:		
  "enabled": true,
	"name": "sloCreateCli",
  "customDescription": "slo as code test",
  "useRateMetric": false,
  "metricRate": "builtin:service.successes.server.rate",
  "metricNumerator": "builtin:service.errors.fivexx.successCount:splitBy()"
  "metricDenominator": "builtin:service.requestCount.server:splitBy()",
	"evaluationType": "AGGREGATE",
	"filter": "type(\"SERVICE\"),entityName(\"[prod]client-login-bff\")",
	"target": 95,
	"warning": 97.5,
	"timeframe": "-1d"

